import FiguraConfirmPassword from "./FiguraInputComponents/FiguraConfirmPassword.jsx"
import FiguraTimeMilitary from "./FiguraInputComponents/FiguraTimeMilitary.jsx"
import FiguraSubmitBtn from "./FiguraSupportingComponents/FiguraSubmitBtn.jsx"
import FiguraButtonGroup from "./FiguraInputComponents/FiguraButtonGroup.jsx"
import FiguraResetBtn from "./FiguraSupportingComponents/FiguraResetBtn.jsx"
import FiguraDateLocal from "./FiguraInputComponents/FiguraDateLocal.jsx"
import FiguraButton from "./FiguraSupportingComponents/FiguraButton.jsx"
import FiguraPassword from "./FiguraInputComponents/FiguraPassword.jsx"
import FiguraTextArea from "./FiguraInputComponents/FiguraTextArea.jsx"
import FiguraCheckBox from "./FiguraInputComponents/FiguraCheckBox.jsx"
import FiguraLabel from "./FiguraSupportingComponents/FiguraLabel.jsx"
import FiguraTitle from "./FiguraSupportingComponents/FiguraTitle.jsx"
import FiguraNumber from "./FiguraInputComponents/FiguraNumber.jsx"
import FiguraSelect from "./FiguraInputComponents/FiguraSelect.jsx"
import FiguraHidden from "./FiguraInputComponents/FiguraHidden.jsx"
import FiguraColor from "./FiguraInputComponents/FiguraColor.jsx"
import FiguraPhone from "./FiguraInputComponents/FiguraPhone.jsx"
import FiguraRadio from "./FiguraInputComponents/FiguraRadio.jsx"
import FiguraRange from "./FiguraInputComponents/FiguraRange.jsx"
import FiguraEmail from "./FiguraInputComponents/FiguraEmail.jsx"
import FiguraMonth from "./FiguraInputComponents/FiguraMonth.jsx"
import FiguraWeek from "./FiguraInputComponents/FiguraWeek.jsx"
import FiguraDate from "./FiguraInputComponents/FiguraDate.jsx"
import FiguraTime from "./FiguraInputComponents/FiguraTime.jsx"
import FiguraFile from "./FiguraInputComponents/FiguraFile.jsx"
import FiguraText from "./FiguraInputComponents/FiguraText.jsx"
import FiguraUrl from "./FiguraInputComponents/FiguraUrl.jsx"
import Figura from "./Figura.jsx"
import "./styles.css.jsx"

export { FiguraConfirmPassword };
export { FiguraTimeMilitary };
export { FiguraButtonGroup };
export { FiguraSubmitBtn };
export { FiguraDateLocal };
export { FiguraResetBtn };
export { FiguraTextArea };
export { FiguraPassword };
export { FiguraCheckBox };
export { FiguraNumber };
export { FiguraSelect };
export { FiguraHidden };
export { FiguraButton };
export { FiguraColor };
export { FiguraPhone };
export { FiguraRange };
export { FiguraRadio };
export { FiguraEmail };
export { FiguraLabel };
export { FiguraTitle };
export { FiguraMonth };
export { FiguraWeek };
export { FiguraDate };
export { FiguraTime };
export { FiguraFile };
export { FiguraText };
export { FiguraUrl };
export { Figura };