import FiguraTimeMilitary from "./FiguraInputComponents/FiguraTimeMilitary";
import FiguraSubmitBtn from "./FiguraSupportingComponents/FiguraSubmitBtn";
import FiguraPassword from "./FiguraInputComponents/FiguraPassword";
import FiguraTextArea from "./FiguraInputComponents/FiguraTextArea";
import FiguraCheckBox from "./FiguraInputComponents/FiguraCheckBox";
import FiguraLabel from "./FiguraSupportingComponents/FiguraLabel";
import FiguraTitle from "./FiguraSupportingComponents/FiguraTitle";
import FiguraSelect from "./FiguraInputComponents/FiguraSelect";
import FiguraPhone from "./FiguraInputComponents/FiguraPhone";
import FiguraEmail from "./FiguraInputComponents/FiguraEmail";
import FiguraText from "./FiguraInputComponents/FiguraText";
import Figura from "./Figura";
import "./styles.css";

export { FiguraTimeMilitary };
export { FiguraSubmitBtn };
export { FiguraTextArea };
export { FiguraPassword };
export { FiguraCheckBox };
export { FiguraSelect };
export { FiguraPhone };
export { FiguraEmail };
export { FiguraLabel };
export { FiguraTitle };
export { FiguraText };
export { Figura };